Features
ricardo123321/Enumerables pull request #1
Opened 2020-04-30 00:11 UTC by ricardo123321

this are replicas of the Enumerable methods that can be found on ruby and were created making use of the call and yield method, I also make use of the self and have an example of the injection code

2020-04-30 14:17 UTC, shshamim63 requested changes
## Status :traffic_light: Required Changes :tractor: 
___
Hi @ricardo123321 :wave: ,
I liked the way you have kept your code really simple. But to get an approval of the project, you have to cover some edge case of those methods too. But the amazing thing is they are very easy to cover. Let's get to the info.
:warning: You have followed the wrong git flow. Check the remember to section of this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421589/). I hope that you will follow the correct flow from your next project. Else the PR can be marked as invalid.
___
### :spades: Mandatory Changes :spades: 
___
1. Please cover the edge case of the methods that are mentioned below by following the comment.
- my_each
- my_each_with_index
- my_select
- my_all?
- my_none?
- my_any?
- my_map
- my_inject
2. I can not see the methods names my_count. Did you forgot to add it? `my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
3. Please fix your multiply_els with the comment below.
4. The title of the PR is not self-descriptive. Can you change it with a more elaborate one?
5. The Readme does not loop interesting. Can you add more info like which document you followed to figure them out., or the names of the methods?
___
##### Please fix the issues mentioned above and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_each` identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)) ``
- Should return an enumerator if no block given.

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
___
- Should return an enumerator if no block is given.
- Calls the given block once for each element in self, the block should accept two values (value, index). What is the index in your code? you have not declared it.

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_select` identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- Should return an enumerator if no block given.

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- when no block or argument is given returns true if at least one of the collection is not false or nil
```ruby
[1, 2, 3].my_any? #should return true
[1, 2, nil].my_any? #should return true
[false, false, nil].my_any? #should return false
```
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
```ruby
[1, 2, 3].my_any?(Integer) #should return true
[1, 'demo', false].my_any?(Integer) #should return true
['demo', false, nil].my_any?(Integer) #should return false
```
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
```ruby
%w[dog door rod blade].my_any?(/t/)    #should return false.
%w[dog door rod blade].my_any?(/d/)   #should return true.
```
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
```ruby
[1, 2, 3].my_any?(3)   #should return true
[1, 2, 2].my_any?(3)   #should return false
```

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)) 
- when no block or argument is given, returns true when none of the collection members are false or nil
```ruby
[1, 2, 3].my_all? #should return true
[1, 2, nil].my_all? #should return false
[1, false, nil].my_all? #should return false
```
- when a class is passed as an argument returns true if all of the collection is a member of such class
```ruby
[1, 2, 3].my_all?(Integer) #should return true
[1, 2, nil].my_all?(Integer) #should return false
```
- when a Regex is passed as an argument returns true if all of the collection matches the Regex
```ruby
%w[dog door rod blade].my_all?(/d/)   #should return true.
%w[dog door rod blade].my_all?(/t/)   #should return false.
```
- when a pattern other than Regex or a Class is given, returns true if all of the collection matches the pattern
```ruby
[3, 3, 3].my_all?(3) #should return true
[3, 3, 1].my_all?(3) #should return false
```

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- when no block or argument is given returns true only if none of the collection members is true
```ruby
[false, nil, false].my_none? #should return true
[1, 'demo', 2.2].my_none? #should return false
```
- when a class is passed as an argument returns true if none of the collection is a member of such class
```ruby
[1, 2, 3].my_none?(String)  #should return true
['1', '2', '3'].my_none?(String)  #should return false
```
- when a Regex is passed as an argument returns true only if none of the collection matches the Regex
```ruby
%w[dog door rod blade].my_none?(/z/)   #should return true
%w[dog door rod blade].my_none?(/d/)   #should return false
```
- when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
```ruby
[1, 2, 4].my_none?(3) #should return true
[1, 2, 3].my_none?(3) #should return false
```

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- returns an Enumerator if no block is given
- returns a new array with the results of running block once for every element in enum
```ruby
block = proc { |num| num < (1 + 10) / 2 }
[1, 2 ,3].my_map(&block)   #should return [1, 2, 3]
[6, 7 ,5].my_map { |num| num > 5 }   #should also return [6, 7]
```

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  end
`my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- combines all elements of enum by applying a binary operation, specified by a block
```ruby
[1, 2, 3].my_inject { |memo, num| memo + num } #should return 6
[1, 2, 3].my_inject(1) { |memo, num| memo + num } #should return 7
```
- when a symbol is specified combines each element of the collection by applying the symbol as a named method
```ruby
[1, 2, 3].my_inject(:+)  #should return 6
[1, 2, 3].my_inject(1, :+)  #should return 7
```

2020-04-30 14:17 UTC, shshamim63 commented on enumerables.rb
> +  [2, 4, 5].multiply_els
`multiply_els` method. it uses `my_inject` as described on Odin ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/multiply_els.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)). Remember, it is not an enumerable method, so should be placed outside of the module.
```ruby
def multiply_els(arr)
  arr.my_inject(2, :*)
end
```

2020-05-04 04:37 UTC, uryelah requested changes
Hello **Ricardo Vera Trallero**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, good job with adding some more details to your code 🌟**

A lot of the fundamental behavior of each Enumerable methods is missing still.  [Make sure you read the specifications of the enumerable module, one by one, and compare it with your code](https://ruby-doc.org/core-2.7.1/Enumerable.html). 

Try also to re-use your own code, you could use my_each_with_index instead of while loops in most of the cases.

You can do it! After you are done with this your ruby foundation will be solid as a rock!💪 

---------     

## Required Changes 🏗 👷‍♀ 

----

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +      arr
- [ ] When no block is given my_each should return an Enumerator. 
Pay attention, an Array and an Enumerator are different classes, they are not the same.
Also remember that my_each could also work with a Range.
Make sure you return an Enumerator in your else, even if the seld if an Array or Range.
https://ruby-doc.org/core-2.6/Enumerator.html

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +      arr
- [ ] Same issue as my_each here. Return an Enumerator, not just the self. You could try to find a way to convert the self to an Enumerator for example.

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +      arr
- [ ] Same Enumerator return issue from above.

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +      to_change = false unless yield(arr[i])
- [ ] my_all? should also work when no block is given.
[Check the documentation on all? here.](https://ruby-doc.org/core-2.7.1/Enumerable.html#method-i-all-3F)

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +      to_change = false unless yield(arr[i])
Ex: 
[1,3,'foo', false].all?
=> false

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +      i += 1
- [ ] my_all should also accept a class, a regex, or a patter(like a number, string, etc), as an argument. Make sure to include those conditions in your code.

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +  def my_any?(arg = nil)
- [ ] my_any should accept a Class or Regex as arguments. Make sure to add conditions to test for those.

- [ ] my_any should also work without a block or argument, in that case it returns tru is any value at all is truthy.

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +  def my_none?
- [ ] my_none should still work without a block or an argument. It returns true if all items are falsy in this case.
- [ ] Make sure to add conditions that take into account getting a Regex, Class, or another pattern as an argument.

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +      arr.my_each { total += 1 }
- [ ] Please don't use the original #count method to make your my_count.
You can use something simple like length, size, or reuse your own my_each or my_each_with_index methods.

- [ ] my_count should also accept an argument and count the number of times it shows up in the self.

- [ ] my_count should also accept a block and in that case count the number of elements yielding a true value.

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +    while i < arr.count
- [ ] my_map should return an Enumerator if no block is given.

- [ ] my_map doesn't accept arguments, just blocks. Please remove the 'the_proc' argument.

2020-05-04 04:37 UTC, uryelah commented on enumerables.rb
> +  def my_inject(start_value = 0, operator = nil)
- [ ] my_inject should also accept a block. Make to add that condition.

- [ ] What happens if there's no start_value and only an operator is used as the sole operator? Make sure it works the same as [1,2,3,4,5].inject(:+) does.

2020-05-04 04:39 UTC, uryelah commented
**Kindly fix the REQUIRED issues and send another code review request.**

As a tip, always test your code on the irb console every time you change a line of code. Make sure to also check if the behavior you get is the same as the original methods.
Use different arrays and ranges with different contents and lengths to test your code too.

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-06 00:48 UTC, kobiyoyo requested changes
## Hi @ricardo123321      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far , but there are few more things required. 
### General
- [ ] `my_each_with_index`  
- it calls the given block once for each element in self
##### For example
````ruby
      my_each_output = ' ' 
      my_each_output_two = ' ' 
      block = proc { |y, x| my_each_output += "Hello: #{y}, in: #{x}\n" }
      block_two = proc { |y, x| my_each_output_two += "Hello: #{y}, in: #{x}\n" }
      [1,2,32,32,3,21,1,23,12].each_with_index(&block_two)
      [1,2,32,32,3,21,1,23,12].my_each_with_index(&block)
       p my_each_output ==  my_each_output_two ` this should return true
````
- [ ] `my_any?`:
- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`

- [ ] `my_count`
- counts the number of elements yielding a true value if a block is given
`block = proc { |num| num < (2 + 24) / 2 }`
`p [23,13,12,43].my_count(&block)` should return 1

- [ ] `my_map` 
- returns an Enumerator if no block is given:
  `p [1, 2, 3].my_map` returns `#<Enumerator>`
- [ ] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method
`p (5..10).my_inject(2, :*) - should return 302400`
- Combines all elements of enum by applying a binary operation, specified by a block:
````ruby
 p (1..5).my_inject(4) { |prod, n| prod * n } should return the same result as inject
````
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-05-07 23:33 UTC, kobiyoyo requested changes
## Hi @ricardo123321      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far , The changes I specified earlier has not been implemented, not even one. Let fix all errors as specified previously. 
##### Note: For next project use Gitflow not Github .
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-05-08 20:25 UTC, shshamim63 requested changes
### Status :traffic_light: Changes Required :1234: 
___
Hi @ricardo123321 :wave: ,
Almost there. You just need to cover some simple and easy edge cases. Let's get to them.
___
### :spades: Mandatory Changes :spades:
___
1. Your multiply_els is not functional. So check my comments related to that and fix it.
2. my_inject is missing some edge cases. Check the comment on the code block.
3. You should not alter the default rubocop config file. check out this [link](https://github.com/microverseinc/linters-config/tree/master/ruby) for more explanation
![image](https://user-images.githubusercontent.com/38625956/81445961-c0deb280-919b-11ea-8ffb-caef3f928169.png).
___
:warning: Based on the pull request it seems that you are not following the right gitflow, As the previous reviewer did not inform about it, so I am not raising any issue on it. But remember to follow the current gitflow in your next project else that could declare as invalid.
___
#### Please fix the issues mentioned above and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-08 20:25 UTC, shshamim63 commented on enumerables.rb
> +[2, 4, 5].multiply_els
Did you execute the code? Cause while I tried, faced an error. Based on the instruction of the multiply_els, what I can get is, it is not an enumerable method. It accepts an array as an argument and performs multiplication functionality through my_inject. So the code should looks like
```ruby
def multiply_els(array)
  array.my_inject(:*)
end
p multiply_els([1, 2, 3])
```

2020-05-08 20:25 UTC, shshamim63 commented on enumerables.rb
> +end
`my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- combines all elements of enum by applying a binary operation, specified by a block
```ruby
%w[dog door rod blade].my_inject {|memo, word| memo.length > word.length ? memo : word}  #should return 'blade'
```
Check your to_check for this criteria. The answer is in there.
- when a symbol is specified combines each element of the collection by applying the symbol as a named method
```ruby
[1, 2, 3].my_inject(:+)  #should return 6
```
But while I tried to execute, I got an error.

2020-05-08 20:25 UTC, shshamim63 commented on enumerables.rb
> +      end
Don't you trust your own my_each method? If you are confused, I am assuring you, your my_each works totally fine. Now there is a better way to handle this symbol. You can use the send method. Check out this [example](https://stackoverflow.com/questions/3337285/what-does-send-do-in-ruby).

2020-05-10 01:42 UTC, Dandush03 reviewed
# Status: :red_circle: Required Change :red_circle: 

## Hey! :wave: 

### You've done great work so far! GOOD JOB :muscle: 

But sadly you didn't manage to succeed in the las 2 test of #my_inject method. Below i will get you some recommendations you should implement in order to get it through. Don't forget that #my_inject should behave in its core as #inject

## :red_circle: But before moving forward I should strongly advise you to create a develop branch and create a PR to it and only then submit this project. since I'm supposed to mark this project as invalid from the bad practice of git-flow which I'm not doing on this occasion since my colleagues didn't notice it so far.

check out this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) for more info

2020-05-10 01:42 UTC, Dandush03 commented on enumerables.rb
> +end
I highly recommend you to fallow @uryelah  comments regarding this, basically, you've made 2 mistakes the first one would be to check the operator, there is a way more efficient way of doing it but essentially they are not relevant if you build this method properly

the second one but more important is that #my_inject only receives an operator, so the first argument you're asking is never submitted and it's crashing the method. 
maybe what you need is to find the starting of a Range and you could do so with the shift or pop method, I'll let you dig into it ;)

If you need any help with this issue, let me know thought slack on Monday

## Happy Coding

### Daniel Laloush

2020-05-12 07:05 UTC, closed without merging